services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "$DJANGO_SERVER_PORT:8000"
    depends_on:
      - db

    healthcheck:
      test: [ "CMD-SHELL", "arg" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  db:
    image: postgres:10-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=$POSTGRES_DBNAME
      - POSTGRES_USER=$POSTGRES_DBUSER
      - POSTGRES_PASSWORD=$POSTGRES_DBPASSWORD
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
